### ISSUE TITLE
Does it use some paid APIs?

### ISSUE THREAD

**Issue by Desintegrator** [nipunru/nsfw-detector-android#1]
Is it free of charge or uses some paid Firebase/MlKit/etc APIs?

**Comment by nipunru** [comment]
Since this lib is using local ml model, this is free.

**Comment by nipunru** [comment]
If you need, please retrain your model from this dataset.
https://www.reddit.com/r/datasets/comments/c24ak4/dataset_image_classification_dataset_for_porn/
