### ISSUE TITLE
While Added Dependency to Gradle 

### ISSUE THREAD

**Issue by logicgupta** [nipunru/nsfw-detector-android#2]
## Getting this error while adding Gradle dependecy
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

**Comment by nipunru** [comment]
This may help you
https://github.com/google/play-services-plugins/issues/153

**Comment by nipunru** [comment]
Hope this is addressed.
