### ISSUE TITLE
How to deploy it for firebase remote call?

### ISSUE THREAD

**Issue by akshaaatt** [nipunru/nsfw-detector-android#3]
Please let me know how I could not include the 5MB model in the app and rather call it from cloud?

**Comment by nipunru** [comment]
Hope this may help you.
https://firebase.google.com/docs/ml-kit/android/use-custom-models

`val remoteModel = FirebaseCustomRemoteModel.Builder("your_model").build()`

**Comment by akshaaatt** [comment]
It doesn't work the way I want it to. Could you upload a sample if you could calling this exact model from the firebase remote?

**Comment by akshaaatt** [comment]
Any progress?
