### ISSUE TITLE
Duplicate Class issue is happening while i am trying to add ml using firebase bom on the latest version of everything

### ISSUE THREAD

**Issue by aishik212** [nipunru/nsfw-detector-android#4]
Duplicate class com.google.android.gms.internal.vision.zze found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzf found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzg found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzh found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzi found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzv found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzw found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)

this is the error message
![Screenshot_20210105_214729](https://user-images.githubusercontent.com/41963730/103670511-aaddf780-4f9f-11eb-9f61-ce00ec619e16.png)

**Comment by imherrera** [comment]
same issue here :/

**Comment by BismeetSingh** [comment]
Use the workaround here : https://firebase.google.com/support/release-notes/android#mlkit-self-serve-fixes

**Comment by nnkphbs** [comment]
Same issue

**Comment by nnkphbs** [comment]
I found a solution. Add this:


    implementation 'com.google.android.gms:play-services-vision:20.1.1'
    implementation 'com.google.android.gms:play-services-vision-common:19.1.1'

**Comment by 88Roman88** [comment]
Using BOM is the most nature way to solve this issue
implementation(platform("com.google.firebase:firebase-bom:${Versions.firebase}"))
        
implement("com.google.firebase:firebase-ml-vision")
implement("com.google.firebase:firebase-ml-vision-automl")
implement("com.google.firebase:firebase-ml-model-interpreter")

**Comment by aliraza96** [comment]
Hi everyone, to anyone, who's facing this issue. 
Just use this BOM version of Firebase, as it's the only version, that supports all three modules

implementation platform('com.google.firebase:firebase-bom:24.5.0')

And after that, use these

implementation 'com.google.firebase:firebase-ml-vision'
implementation 'com.google.firebase:firebase-ml-vision-automl'
implementation 'com.google.firebase:firebase-ml-model-interpreter'
