### ISSUE TITLE
Error when using Text Recognition dependency

### ISSUE THREAD

**Issue by hilmyas** [nipunru/nsfw-detector-android#6]
add this to app's build.gradle:
implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.1.3'

runtime error when using nfsw detector:
java.lang.NoSuchFieldError: No static field AUTOML of type Lcom/google/mlkit/common/sdkinternal/ModelType;

**Comment by nipunru** [comment]
This library only using the below dependence.

api "com.google.firebase:firebase-ml-vision:<latest_version>"
implementation "com.google.firebase:firebase-ml-vision-automl:<latest_version>"
implementation "com.google.firebase:firebase-ml-model-interpreter:<latest_version>"

This may help
https://developers.google.com/android/reference/com/google/mlkit/common/model/package-summary

**Comment by hilmyas** [comment]
When I want to use your library combined with this dependency:
implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.1.3',

the crash always occurs
