### ISSUE TITLE
Can this be detected on device?

### ISSUE THREAD

**Issue by manwithsteelnerves** [nipunru/nsfw-detector-android#8]
Is the model available to detect on-device(Android) through ML Kit?

**Comment by thrishool0145** [comment]
Is this maintained? I want to use this in my project. Pls reply

**Comment by nipunru** [comment]
Let me know if you get any issue!

**Comment by nipunru** [comment]
> Is the model available to detect on-device(Android) through ML Kit?

Yes

**Comment by thrishool0145** [comment]
Hi. Could you please provide the java code for the following kotlin code
NSFWDetector.isNSFW(bitmap,confidenceThreshold) { isNSFW, confidence, image ->
    if (isNSFW){
        Toast.makeText(this, "NSFW with confidence: $confidence", Toast.LENGTH_SHORT).show()
    } else {
        Toast.makeText(this, "SFW with confidence: $confidence", Toast.LENGTH_SHORT).show()
    }
}

I am facing lamda issues.

**Comment by nipunru** [comment]
I believe you may need to do somthing like this;

```
NSFWDetector.isNSFW(bitmap,confidenceThreshold, this::result)

private Unit failure(Boolean isNSFW, Float confidence, Bitmap image ) {
        // do something java here
        return Unit.INSTANCE; //This is important
}

```

I did not test this and read more on [here](https://stackoverflow.com/questions/53338638/how-to-call-kotlin-function-with-function-as-parameter-in-java-code). Also Java 8 is directly supported as far I know
